GT_Output.AddString("GT_Event", "enUS", "AddEvent", "Adding new event: \"%s\" for \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "BadTrigger", "Triggered event \"%s\", but no addons are currently registered for it.")
GT_Output.AddString("GT_Event", "enUS", "Calling", "Passing event \"%s\" to \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "InvalidAdd", "Invalid event registration call: \"%s\" for \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "InvalidRemove", "Invalid event unregistration call: \"%s\" for \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "RegisterEvent", "Registering for new event \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "RemoveEvent", "Removing event: \"%s\" for \"%s\".")
GT_Output.AddString("GT_Event", "enUS", "UnregisterEvent", "Unregistering existing event \"%s\".")
